### ISSUE TITLE
Subject is deprecated

### ISSUE THREAD

**Issue by boan-jfm** [kodus/mail#18]
From PHP version 8.1 it is deprecated to give null as `subject` parameter to `preg_match`: https://www.php.net/manual/en/function.preg-match.php

Image
![image](https://user-images.githubusercontent.com/13201214/235654816-54ab34d6-71a0-4817-a9e4-552aac449144.png)
https://tehplayground.com/66bDQ6thbWYTef4D

Code - parameter to methods are nullable
https://github.com/kodus/mail/blob/e391f2b025552376119a4dd08d8b78a88c4281d0/src/Message.php#L325-L327

https://github.com/kodus/mail/blob/e391f2b025552376119a4dd08d8b78a88c4281d0/src/Message.php#L347-L349

**Comment by thomasnordahl-dk** [comment]
Duplicate of #15
